[package]
name = "slammers"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.15.4"
ndarray-linalg = { version = "0.14.1", features = ["openblas-system"] }
termion = "1.5.6"
rand = "0.8.4"
rand_distr = "0.4.2"
